# mk is better (see plan-9)
MKSHELL = ksh

jsmn_lib = -L jsmn -ljsmn
cc = gcc
cflags = -I jsmn -g

binaries = jwrapper_test parm_file_test list_test fifo_test bleat_test id_mgr_test filesys_test  pfx_list_test  vf_config_test

%.o: %.c
	$cc $cflags -c $prereq

all:V: libvfd.a jsmn

lib = libvfd.a
lib_src = jwrapper jw_xapi symtab config ng_flowmgr fifo list_files bleat hot_plug id_mgr filesys
$lib(%.o):N:    %.o
$lib:   ${lib_src:%=$lib(%.o)}
    ksh '(
    set -e
    names="${newprereq//$lib\(}"                  # pluck off lib.*( from each in newprereq
    ar r $lib ${names//\)/} && rm ${names//\)/}   # archive and remove after ditching trailing ) from each name
    ranlib $lib ||true
    )'

# deprecated; now in main .h
#jwrapper.h:	jwrapper.c
#	grep "^extern.*{$" jwrapper.c | sed 's/ {$/;/' >jwrapper.h

# --------- tests ----------------------------------------------------
jwrapper_test:: jwrapper_test.c vfdlib.h jwrapper.o symtab.o
	$cc $cflags jwrapper_test.c  -o jwrapper_test jwrapper.o symtab.o $jsmn_lib

jwrapper_test2:: jwrapper_test2.c vfdlib.h jwrapper.o symtab.o
	$cc $cflags jwrapper_test2.c  -o jwrapper_test2 jwrapper.o symtab.o $jsmn_lib

parm_file_test::	parm_file_test.c $lib
	$cc $cflags parm_file_test.c -o parm_file_test -L. -lvfd $jsmn_lib
	
vf_config_test::	vf_config_test.c $lib
	$cc $cflags vf_config_test.c -o vf_config_test -L. -lvfd $jsmn_lib

fifo_test::	fifo_test.c $lib
	$cc $cflags fifo_test.c -o fifo_test -L. -lvfd $jsmn_lib

bleat_test::	bleat_test.c $lib
	$cc $cflags bleat_test.c -o bleat_test -L. -lvfd $jsmn_lib

list_test::	list_test.c $lib
	$cc $cflags list_test.c -o list_test -L. -lvfd $jsmn_lib

old_list_test::	old_list_test.c $lib
	$cc $cflags old_list_test.c -o old_list_test -L. -lvfd $jsmn_lib

pfx_list_test::	pfx_list_test.c $lib
	$cc $cflags pfx_list_test.c -o pfx_list_test -L. -lvfd $jsmn_lib

id_mgr_test::	id_mgr_test.c $lib
	$cc $cflags id_mgr_test.c -o id_mgr_test -L. -lvfd $jsmn_lib

filesys_test::	filesys_test.c $lib
	$cc $cflags filesys_test.c -o filesys_test -L. -lvfd $jsmn_lib

hot_plug_test::	hot_plug_test.c $lib
	$cc $cflags hot_plug_test.c -o hot_plug_test -L. -lvfd $jsmn_lib


all_tests:V: $binaries

#jwrapper_test jwrapper_test2 parm_file_test vf_config_test fifo_test bleat_test \
#	list_test pfx_list_test id_mgr_test filesys_test hot_plug_test hot_plug_test


test:V:
	ksh jwrapper_test.ksh

nuke:V:
	rm -f *.o *.a $binaries


# ------ clone (if needed) and update and build jsmn -------
jsmn:V:
	if [[ ! -d jsmn ]]
	then
		git clone https://github.com/zserge/jsmn
	fi
	cd jsmn
	git pull
	make
