# mk is better (see plan-9)

jsmn_lib = -L jsmn -ljsmn
cc = gcc
cflags = -I jsmn -g

binaries = jwrapper jwrapper_test

%.o: %.c
	$cc $cflags -c $prereq

all:V: jwrapper jwrapper_test tahlib.a

lib = tahlib.a
lib_src = jwrapper symtab
$lib(%.o):N:    %.o
$lib:   ${lib_src:%=$lib(%.o)}
    ksh '(
    set -e
    names="${newprereq//$lib\(}"                  # pluck off lib.*( from each in newprereq
    ar r $lib ${names//\)/} && rm ${names//\)/}   # archive and remove after ditching trailing ) from each name
    ranlib $lib ||true
    )'

jwrapper.h:	jwrapper.c
	grep "^extern.*{$" jwrapper.c | sed 's/ {$/;/' >jwrapper.h

jwrapper_test: jwrapper_test.c jwrapper.h jwrapper.o symtab.o
	$cc $cflags jwrapper_test.c  -o jwrapper_test jwrapper.o symtab.o $jsmn_lib

test:V:
	ksh jwrapper_test.ksh

nuke:V:
	rm -f *.o *.a $binaries


# ------ clone (if needed) and update and build jsmn -------
jsmn:V:
	if [[ ! -d jsmn ]]
	then
		git clone https://github.com/zserge/jsmn
	fi
	cd jsmn
	git pull
	make
