#!/bin/sh

set -e

echo "running attlrvfd post initialisation..."

# Add the vfd group unless it's already there
if ! getent group vfd >/dev/null
then
   addgroup --quiet --system vfd || true
fi

if [ ! -d /etc/vfd ]
then
	mkdir -p /etc/vfd
fi

if [ $? -ne 0 ]
then
	echo "unable to create /etc/vfd "
	exit 0
fi

if [ ! -d /var/log/vfd ]
then
	mkdir -p /var/log/vfd
fi

if [ $? -ne 0 ]
then
	echo "unable to create /var/log/vfd "
	exit 0
fi

if [ ! -d /var/lib/vfd/config ]
then
	mkdir -p /var/lib/vfd/config
fi

if [ $? -ne 0 ]
then
	echo "unable to create /var/lib/vfd/config "
	exit 0
fi

chgrp vfd /var/lib/vfd/config
chmod 775 /var/lib/vfd/config

if [ -f /etc/vfd/vfd.cfg.sample ]
then
	chmod 0644 /etc/vfd/vfd.cfg.sample
fi

if [ $? -ne 0 ]
then
	echo "no file found /etc/vfd/vfd.cfg.sample"
fi

echo "post initialisation completed"
