#!/bin/sh -e

case "$1" in
	remove)
	if [ -d /var/log/vfd ]; then
	echo "leaving logs in /var/log/vfd for historical purposes"
	fi

	if [ -d /etc/vfd ]; then
	echo "leaving vfd configuration in /etc/vfd for historical purposes"
	fi
    ;;

	purge)
	if [ -f /etc/init/vfd.conf ]; then
	rm -f /etc/init/vfd.conf
	rmdir --ignore-fail-on-non-empty /etc/vfd/
	fi

	if [ -d /var/log/vfd ]; then
	rm -rf /var/log/vfd
	fi

	if [ -d /var/lib/vfd ]; then
	rm -rf /var/lib/vfd
	fi

    if [ -d /etc/vfd ]; then
    rm -rf /etc/vfd/vfd.conf
    fi
    ;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

    *)
    echo "postrm called with unknown argument '$1'" >&2
    exit 1
    ;;
esac
