# plan9 mk

<master.mk

fig_src = vfd_process

all:V: vfd_hackers.pdf 

figures:V: ${fig_src:%=figures/%.eps}

vfd_users.ps::	vfd_hackers.ps
	cp vfd_hackers.ps vfd_users.ps

vfd_hackers.ps:: vfd_hackers.xfm appendix_a.im
	pfm vfd_hackers.xfm vfd_hackers.ps

vfd_hackers.md:: vfd_hackers.xfm
	MARKDOWN=1 tfm vfd_hackers.xfm vfd_hackers.o
	sed 's/^ //' vfd_hackers.o >vfd_hackers.md
	rm vfd_hackers.o

