# plan9 mk

<master.mk

fig_src = vfd_ds_overview vfd_process

all:V: vfd_hackers.pdf vfd_design.pdf

figures:V: ${fig_src:%=figures/%.eps}

vfd_design.ps:: vfd_design.xfm figures
	pfm vfd_design.xfm vfd_design.ps

vfd_hackers.ps:: vfd_hackers.xfm 
	pfm vfd_hackers.xfm vfd_hackers.ps

